#src
print(Platform())
Import('env')

grk_env = env.Clone()
grk_env.Append(CCFLAGS='-DGL_DRAWING')
grk_env.GLSL('shaders')
grk_src = [grk_env.Object('grk_%s.o'%x, x+'.c') for x in ['gl', 'main', 'math', 'logging', 'trades', 'function', 'glmath']]
pixie_exe = grk_env.Program('grk', grk_src, LIBS=['m', 'GLESv2', 'glfw'])

trade_env = env.Clone()
trade_env.Append(CCFLAGS='-DINCLUDE_MAIN')
trade_src = [trade_env.Object('trd_%s.o'%x, x+'.c') for x in ['trades', 'logging']]
merge = trade_env.Program('merge',trade_src, LIBS=[],)
